import { db } from "@/db";
import { products,projects,projectImages,clients,services,heroSlides,testimonials } from "@/db/schema";
import { and,asc,eq,inArray,ne,or } from "drizzle-orm";
export async function getHeroSlides(){return db.select().from(heroSlides).where(eq(heroSlides.active,true)).orderBy(asc(heroSlides.sortOrder))}
export async function getProducts(category?:string){const where=category?and(eq(products.active,true),eq(products.category,category)):eq(products.active,true);return db.select().from(products).where(where).orderBy(asc(products.sortOrder))}
export async function getProductBySlug(slug:string){const [row]=await db.select().from(products).where(and(eq(products.slug,slug),eq(products.active,true)));return row||null}
export async function getProjects(status?:string){const where=status?and(eq(projects.active,true),eq(projects.status,status)):eq(projects.active,true);return db.select().from(projects).where(where).orderBy(asc(projects.sortOrder))}
export async function getProjectBySlug(slug:string){const [row]=await db.select().from(projects).where(and(eq(projects.slug,slug),eq(projects.active,true)));return row||null}
export async function getProjectPortfolio(slug:string){const project=await getProjectBySlug(slug);if(!project)return null;const [client,gallery,related]=await Promise.all([project.clientId?db.select().from(clients).where(eq(clients.id,project.clientId)).then(x=>x[0]||null):null,db.select().from(projectImages).where(eq(projectImages.projectId,project.id)).orderBy(asc(projectImages.sortOrder)),db.select().from(projects).where(and(eq(projects.active,true),ne(projects.id,project.id),or(eq(projects.category,project.category),project.clientId?eq(projects.clientId,project.clientId):eq(projects.category,project.category)))).limit(3)]);return {project,client,gallery,related}}
export async function getClients(){return db.select().from(clients).where(eq(clients.active,true)).orderBy(asc(clients.row),asc(clients.sortOrder))}
export async function getClientBySlug(slug:string){const [row]=await db.select().from(clients).where(and(eq(clients.slug,slug),eq(clients.active,true)));return row||null}
export async function getClientPortfolio(slug:string){const client=await getClientBySlug(slug);if(!client)return null;const [clientProjects,others]=await Promise.all([db.select().from(projects).where(and(eq(projects.clientId,client.id),eq(projects.active,true))).orderBy(asc(projects.sortOrder)),db.select().from(clients).where(and(eq(clients.active,true),ne(clients.id,client.id))).orderBy(asc(clients.sortOrder)).limit(4)]);const gallery=clientProjects.length?await db.select().from(projectImages).where(inArray(projectImages.projectId,clientProjects.map(p=>p.id))).orderBy(asc(projectImages.sortOrder)):[];return {client,projects:clientProjects,gallery,others}}
export async function getTestimonials(){return db.select().from(testimonials).where(eq(testimonials.active,true)).orderBy(asc(testimonials.sortOrder),asc(testimonials.id))}
export async function getServices(){return db.select().from(services).where(eq(services.active,true)).orderBy(asc(services.sortOrder))}
export async function getServiceBySlug(slug:string){const [row]=await db.select().from(services).where(and(eq(services.slug,slug),eq(services.active,true)));return row||null}
