import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader,CTASection } from "@/components/ui";
import { ProductCard } from "@/components/ProductCard";
import { MotionReveal } from "@/components/MotionReveal";
import { getProducts } from "@/lib/queries";
import { PRODUCT_CATEGORIES } from "@/lib/site";
export const metadata:Metadata={title:"HVAC Ducting Products",description:"Explore CMS-managed MSNSS MS and SS HVAC ducting products, accessories, coating systems and manufacturing equipment.",alternates:{canonical:"/products"},openGraph:{title:"HVAC Ducting Products | MSNSS",description:"MS and SS ducting products for commercial, industrial and infrastructure project requirements."}};
export const dynamic="force-dynamic";
export default async function ProductsPage({searchParams}:{searchParams:Promise<{category?:string}>}){const {category}=await searchParams,active=category&&PRODUCT_CATEGORIES.includes(category)?category:undefined;const products=await getProducts(active);return <><PageHeader title={active||"Our Ducting Products"} subtitle="Reliable products manufactured and fabricated for project-specific HVAC and ventilation requirements." crumb="Products"/><section className="relative overflow-hidden bg-white py-14"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(#e2e8f0_1px,transparent_1px),linear-gradient(90deg,#e2e8f0_1px,transparent_1px)] [background-size:42px_42px] [mask-image:linear-gradient(to_bottom,black,transparent_40%)]"/><div className="relative mx-auto max-w-7xl px-6"><MotionReveal className="mx-auto mb-10 max-w-3xl text-center"><span className="text-xs font-bold uppercase tracking-[.2em] text-brand">Manufactured for Project Requirements</span><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">MS &amp; SS Ducting, Components and Accessories</h2><p className="mt-4 leading-7 text-slate-600">Browse active products managed by the MSNSS team. Product materials, dimensions and finishes are confirmed against approved project requirements.</p></MotionReveal><nav aria-label="Product categories" className="mb-10 flex flex-wrap justify-center gap-3"><Link href="/products" className={`rounded-full px-5 py-2 text-sm font-semibold transition ${!active?"bg-brand text-white shadow-md":"border border-slate-300 bg-white text-slate-600 hover:border-brand hover:text-brand"}`}>All</Link>{PRODUCT_CATEGORIES.map(item=><Link key={item} href={`/products?category=${encodeURIComponent(item)}`} className={`rounded-full px-5 py-2 text-sm font-semibold transition ${active===item?"bg-brand text-white shadow-md":"border border-slate-300 bg-white text-slate-600 hover:border-brand hover:text-brand"}`}>{item}</Link>)}</nav>{products.length?<div className="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{products.map((product,index)=><ProductCard key={product.id} product={product} index={index}/>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center"><div className="text-5xl">□</div><h2 className="mt-4 text-lg font-bold">No products published</h2><p className="mt-1 text-slate-500">Products in this category will appear after admin publication.</p></div>}</div></section><CTASection/></>}
