"use client";
import { useState } from "react";
import { PRODUCT_LINKS, SOLUTION_LINKS } from "@/lib/site";

type Result={status:"idle"|"loading"|"success"|"error";message?:string;reference?:string;name?:string};
export function InquiryForm({source="contact"}:{source?:string}){const [result,setResult]=useState<Result>({status:"idle"});
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form).entries());setResult({status:"loading"});try{const r=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw new Error(j.error);setResult({status:"success",reference:j.reference,name:String(data.name)});form.reset()}catch(x){setResult({status:"error",message:(x as Error).message})}}
if(result.status==="success")return <div className="rounded-xl border border-green-200 bg-green-50 p-10 text-center"><div className="text-5xl">✓</div><h3 className="mt-4 text-xl font-bold text-green-800">Inquiry Submitted Successfully</h3><p className="mt-2 text-green-700">Thank you, {result.name}. Our team will review your requirement and contact you.</p><p className="mt-4 text-sm">Your inquiry reference: <strong>{result.reference}</strong></p><button onClick={()=>setResult({status:"idle"})} className="mt-6 rounded-md bg-brand px-6 py-3 text-sm font-semibold text-white">Send Another Inquiry</button></div>;
const cls="w-full rounded-md border border-slate-300 px-4 py-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/20";
return <form onSubmit={submit} className="space-y-4"><input type="hidden" name="source" value={source}/><div className="absolute -left-[9999px]" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
<div className="grid gap-4 sm:grid-cols-2"><Field label="Full Name *"><input name="name" required className={cls}/></Field><Field label="Company Name"><input name="company" className={cls}/></Field><Field label="Email *"><input type="email" name="email" required className={cls}/></Field><Field label="Phone *"><input name="phone" required className={cls}/></Field><Field label="City"><input name="city" className={cls}/></Field><Field label="Project Location"><input name="projectLocation" className={cls}/></Field><Field label="Product"><select name="productInterest" className={cls}><option value="">Select product</option>{PRODUCT_LINKS.map(([n])=><option key={n}>{n}</option>)}</select></Field><Field label="Solution"><select name="solutionInterest" className={cls}><option value="">Select solution</option>{SOLUTION_LINKS.map(([n])=><option key={n}>{n}</option>)}</select></Field><Field label="Project Type"><input name="projectType" className={cls} placeholder="Commercial, industrial..."/></Field><Field label="Quantity / Approx. Area"><input name="quantity" className={cls} placeholder="Example: 500 SQM"/></Field></div>
<Field label="Message *"><textarea name="message" required minLength={10} rows={5} className={cls} placeholder="Tell us about your drawings and requirements..."/></Field>
<label className="flex items-start gap-2 text-sm text-slate-600"><input type="checkbox" name="consent" required className="mt-1"/>I agree to be contacted regarding this inquiry.</label>
{result.status==="error"&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{result.message}</p>}<button disabled={result.status==="loading"} className="w-full rounded-md bg-brand px-6 py-3 text-sm font-semibold text-white hover:bg-brand-dark disabled:opacity-60">{result.status==="loading"?"Submitting...":"Request a Quote"}</button><p className="text-xs text-slate-500">For attachments, submit this form first and reply to the confirmation email with your PDF, drawing or image.</p></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-sm font-medium text-slate-700">{label}</span>{children}</label>}
