"use client";
import Link from "next/link";
import { animate,motion,useMotionValue,useReducedMotion } from "framer-motion";
import { useEffect,useRef } from "react";
import type { Client } from "@/db/schema";

function ClientGroup({items}:{items:Client[]}){return <div className="flex shrink-0 gap-5 pr-5">{items.map(c=><Link key={c.id} href={`/clients/${c.slug}`} title={`View MSNSS portfolio for ${c.name}`} className="group flex h-24 w-48 shrink-0 touch-manipulation items-center justify-center rounded-xl border border-slate-200 bg-white px-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-brand/50 hover:shadow-lg sm:w-56"><img src={c.logoUrl} alt={c.logoAlt||`${c.name} logo`} loading="lazy" className="max-h-14 max-w-full object-contain transition duration-300 group-hover:scale-[1.06]"/></Link>)}</div>}
function Row({items,direction}:{items:Client[];direction:"right"|"left"}){const reduce=useReducedMotion();const x=useMotionValue(direction==="right"?"-50%":"0%");const playback=useRef<ReturnType<typeof animate>|null>(null);useEffect(()=>{if(reduce){x.set("0%");return}playback.current=animate(x,direction==="right"?["-50%","0%"]:["0%","-50%"],{duration:Math.max(24,items.length*7),ease:"linear",repeat:Infinity});return()=>playback.current?.stop()},[direction,items.length,reduce,x]);if(!items.length)return null;if(reduce)return <div className="flex flex-wrap justify-center gap-5 px-5 py-2">{items.map(c=><Link key={c.id} href={`/clients/${c.slug}`} className="flex h-24 w-48 items-center justify-center rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><img src={c.logoUrl} alt={c.logoAlt||`${c.name} logo`} loading="lazy" className="max-h-14 max-w-full object-contain"/></Link>)}</div>;return <div className="overflow-hidden py-2 [mask-image:linear-gradient(to_right,transparent,black_5%,black_95%,transparent)]" onMouseEnter={()=>playback.current?.pause()} onMouseLeave={()=>playback.current?.play()}><motion.div className="flex w-max" style={{x}}><ClientGroup items={items}/><ClientGroup items={items}/></motion.div></div>}
export function TrustedClients({clients}:{clients:Client[]}){if(!clients.length)return null;const row1=clients.filter(c=>c.row===1),row2=clients.filter(c=>c.row===2);return <section className="overflow-hidden bg-slate-50 py-14"><div className="mx-auto max-w-6xl px-6 text-center"><span className="text-sm font-bold uppercase tracking-wider text-brand">Trusted Clients</span><h2 className="mt-2 text-3xl font-extrabold text-ink sm:text-4xl">Trusted by Businesses That Demand Precision.</h2><p className="mx-auto mt-3 max-w-3xl text-slate-600">Our work is built around quality, responsiveness and dependable project execution.</p></div><div className="mt-9 space-y-4"><Row items={row1} direction="right"/><Row items={row2} direction="left"/></div></section>}
