import type { Metadata } from "next";
import Link from "next/link";
import { MotionReveal } from "@/components/MotionReveal";

import { CTASection,PageHeader } from "@/components/ui";
import { getServices } from "@/lib/queries";
export const dynamic="force-dynamic";
export const metadata:Metadata={title:"HVAC Ducting Solutions",description:"Explore MSNSS duct manufacturing, fabrication, installation, insulation, coating and surface treatment solutions.",alternates:{canonical:"/solutions"},openGraph:{title:"HVAC Ducting Solutions | MSNSS",description:"Manufacturing, fabrication, finishing and installation support for HVAC ducting projects."}};
export default async function SolutionsPage(){const solutions=await getServices();return <><PageHeader title="Complete Ducting Solutions" subtitle="Manufacturing, fabrication, finishing and installation support for project requirements." crumb="Solutions"/><section className="relative overflow-hidden bg-white py-16"><div className="absolute inset-0 opacity-35 [background-image:radial-gradient(#0e7cc4_1px,transparent_1px)] [background-size:28px_28px] [mask-image:linear-gradient(to_bottom,black,transparent_55%)]"/><div className="relative mx-auto max-w-7xl px-6"><MotionReveal className="mx-auto mb-12 max-w-3xl text-center"><span className="text-xs font-bold uppercase tracking-[.2em] text-brand">Manufacturer · Fabricator · Installer</span><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">Support Across the Ducting Project Cycle</h2><p className="mt-4 text-lg leading-8 text-slate-600">Choose a solution to understand the work currently offered by MSNSS. All published solution content is controlled through the existing admin CMS.</p></MotionReveal>{solutions.length?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{solutions.map((solution,index)=><MotionReveal key={solution.id} delay={Math.min(index*.06,.24)} className="h-full"><Link href={`/solutions/${solution.slug}`} className="group relative flex h-full min-h-72 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-brand/50 hover:shadow-xl"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-brand-light transition duration-500 group-hover:scale-125"/><div className="relative flex items-center justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-950 text-2xl text-white shadow-lg transition group-hover:scale-110 group-hover:bg-brand">{solution.icon}</span><span className="text-sm font-extrabold text-brand">{String(index+1).padStart(2,"0")}</span></div><h2 className="relative mt-6 text-xl font-bold group-hover:text-brand">{solution.name}</h2><p className="relative mt-3 flex-1 text-sm leading-7 text-slate-600">{solution.shortDescription}</p><span className="relative mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand">View Solution <span className="transition group-hover:translate-x-1">→</span></span></Link></MotionReveal>)}</div>:<div className="rounded-xl border border-dashed py-16 text-center"><h2 className="text-xl font-bold">Solutions are being updated</h2><p className="mt-2 text-slate-500">Please contact MSNSS to discuss your requirement.</p></div>}</div></section><CTASection/></>}
